extends Area2D


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		var mouseMotion = event as InputEventMouseMotion
		position = mouseMotion.position


func _on_body_entered(body: Node2D) -> void:
	print(body.get_name(), " overlaps with me")
